server:
  port: 8083

spring:
  application:
    name: notification-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://bt-postgres:5432/trackforge_notifications}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}

    consumer:
      group-id: notification-service
      auto-offset-reset: earliest

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "*"

sendgrid:
  api-key: ${SENDGRID_API_KEY:}

from:
  email: ${FROM_EMAIL:noreply@trackforge.io}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics

  metrics:
    export:
      prometheus:
        enabled: true